import 'package:flutter/material.dart';
import '../providers/app_provider.dart';
import 'package:provider/provider.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'es': {
      'login_title': 'INICIO DE SESIÓN',
      'register_title': 'Registro de Operador',
      'email_hint': 'Correo Electrónico',
      'pass_hint': 'Contraseña',
      'login_btn': 'Ingresar al Sistema',
      'register_btn': 'Crear Cuenta',
      'settings': 'Configuración',
      'language': 'Idioma',
      'font_size': 'Tamaño de Fuente',
      'notification_target': 'Enviar Alertas a',
      'theme': 'Apariencia (Tema)',
      'logout': 'Cerrar Sesión',
      'delete_account': 'Destruir Cuenta',
      'alerts': 'Alertas',
      'dashboard': 'Dashboard',
      'settings_title': 'Configuración del Sistema',
      'theme_title': 'Apariencia del Sistema',
      'theme_subtitle': 'Alternar Modo Claro / Oscuro (Brillante)',
      'lang_title': 'Idioma del Sistema',
      'danger_zone': 'ZONA DE PELIGRO',
      'danger_zone_desc': 'Borrar tu cuenta eliminará todos tus datos encriptados de la base de datos local y cerrará tu sesión permanentemente. Esta acción no se puede deshacer.',
      'delete_account_confirm': 'BORRAR CUENTA DEFINITIVAMENTE',
      'show_danger_zone': 'Mostrar Zona de Peligro',
      'hide_danger_zone': 'Ocultar Zona de Peligro',
      'danger_zone_sub': 'Opciones avanzadas de cuenta',
      'tactical_alerts_log': 'REGISTRO DE ALERTAS TÁCTICO',
      'export_csv': 'EXPORTAR CSV',
      'col_time': 'HORA',
      'col_plate': 'PLACA',
      'col_brand_color': 'MARCA/COLOR',
      'col_confidence': 'CONFIANZA',
      'col_status': 'ESTADO',
      'recent_captures': 'CAPTURAS RECIENTES',
      'initializing_feed': 'INICIALIZANDO TRANSMISIÓN DE VIDEO...',
      'analyzing_traffic': 'ANALIZANDO TRÁFICO...',
    },
    'en': {
      'login_title': 'LOGIN',
      'register_title': 'Operator Registration',
      'email_hint': 'Email Address',
      'pass_hint': 'Password',
      'login_btn': 'Enter System',
      'register_btn': 'Create Account',
      'settings': 'Settings',
      'language': 'Language',
      'font_size': 'Font Size',
      'notification_target': 'Send Alerts To',
      'theme': 'Appearance (Theme)',
      'logout': 'Log Out',
      'delete_account': 'Destroy Account',
      'alerts': 'Alerts',
      'dashboard': 'Dashboard',
      'settings_title': 'System Settings',
      'theme_title': 'System Appearance',
      'theme_subtitle': 'Toggle Light / Dark Mode (Bright)',
      'lang_title': 'System Language',
      'danger_zone': 'DANGER ZONE',
      'danger_zone_desc': 'Deleting your account will erase all your encrypted data from the local database and log you out permanently. This action cannot be undone.',
      'delete_account_confirm': 'DELETE ACCOUNT PERMANENTLY',
      'show_danger_zone': 'Show Danger Zone',
      'hide_danger_zone': 'Hide Danger Zone',
      'danger_zone_sub': 'Advanced account options',
      'tactical_alerts_log': 'TACTICAL ALERTS LOG',
      'export_csv': 'EXPORT CSV',
      'col_time': 'TIME',
      'col_plate': 'PLATE',
      'col_brand_color': 'BRAND/COLOR',
      'col_confidence': 'CONFIDENCE',
      'col_status': 'STATUS',
      'recent_captures': 'RECENT CAPTURES',
      'initializing_feed': 'INITIALIZING VIDEO FEED...',
      'analyzing_traffic': 'ANALYZING TRAFFIC...',
    },
    'fr': {
      'login_title': 'CONNEXION',
      'register_title': 'Inscription Opérateur',
      'email_hint': 'Adresse E-mail',
      'pass_hint': 'Mot de Passe',
      'login_btn': 'Entrer dans le Système',
      'register_btn': 'Créer un Compte',
      'settings': 'Paramètres',
      'language': 'Langue',
      'font_size': 'Taille de Police',
      'notification_target': 'Envoyer Alertes À',
      'theme': 'Apparence (Thème)',
      'logout': 'Se Déconnecter',
      'delete_account': 'Détruire le Compte',
      'alerts': 'Alertes',
      'dashboard': 'Tableau de Bord',
      'settings_title': 'Paramètres du Système',
      'theme_title': 'Apparence du Système',
      'theme_subtitle': 'Basculer entre Mode Clair / Sombre',
      'lang_title': 'Langue du Système',
      'danger_zone': 'ZONE DE DANGER',
      'danger_zone_desc': 'Supprimer votre compte effacera toutes vos données cryptées de la base de données locale et vous déconnectera définitivement. Cette action est irréversible.',
      'delete_account_confirm': 'SUPPRIMER LE COMPTE DÉFINITIVEMENT',
      'show_danger_zone': 'Afficher la Zone de Danger',
      'hide_danger_zone': 'Masquer la Zone de Danger',
      'danger_zone_sub': 'Options de compte avancées',
      'tactical_alerts_log': 'REGISTRE D\'ALERTES TACTIQUES',
      'export_csv': 'EXPORTER CSV',
      'col_time': 'HEURE',
      'col_plate': 'PLAQUE',
      'col_brand_color': 'MARQUE/COULEUR',
      'col_confidence': 'CONFIANCE',
      'col_status': 'ÉTAT',
      'recent_captures': 'CAPTURES RÉCENTES',
      'initializing_feed': 'INITIALISATION DU FLUX VIDÉO...',
      'analyzing_traffic': 'ANALYSE DU TRAFIC EN COURS...',
    },
    'de': {
      'login_title': 'ANMELDUNG',
      'register_title': 'Betreiberregistrierung',
      'email_hint': 'E-Mail-Adresse',
      'pass_hint': 'Passwort',
      'login_btn': 'System betreten',
      'register_btn': 'Konto erstellen',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'font_size': 'Schriftgröße',
      'notification_target': 'Warnungen senden an',
      'theme': 'Erscheinungsbild',
      'logout': 'Abmelden',
      'delete_account': 'Konto zerstören',
      'alerts': 'Warnungen',
      'dashboard': 'Armaturenbrett',
      'settings_title': 'Systemeinstellungen',
      'theme_title': 'System-Erscheinungsbild',
      'theme_subtitle': 'Hell-/Dunkelmodus umschalten',
      'lang_title': 'Systemsprache',
      'danger_zone': 'GEFAHRENBEREICH',
      'danger_zone_desc': 'Das Löschen Ihres Kontos löscht alle Ihre verschlüsselten Daten aus der lokalen Datenbank und meldet Sie dauerhaft ab. Diese Aktion kann nicht rückgängig gemacht werden.',
      'delete_account_confirm': 'KONTO DAUERHAFT LÖSCHEN',
      'show_danger_zone': 'Gefahrenbereich anzeigen',
      'hide_danger_zone': 'Gefahrenbereich ausblenden',
      'danger_zone_sub': 'Erweiterte Kontoeinstellungen',
      'tactical_alerts_log': 'TAKTIK-ALARMPROTOKOLL',
      'export_csv': 'CSV EXPORTIEREN',
      'col_time': 'UHRZEIT',
      'col_plate': 'KENNZEICHEN',
      'col_brand_color': 'MARKE/FARBE',
      'col_confidence': 'KONFIDENZ',
      'col_status': 'STATUS',
      'recent_captures': 'NEUESTE ERFASSUNGEN',
      'initializing_feed': 'VIDEO-STREAM WIRD INITIALISIERT...',
      'analyzing_traffic': 'VERKEHRSANALYSE LÄUFT...',
    },
    'pt': {
      'login_title': 'CONECTAR-SE',
      'register_title': 'Registro de Operador',
      'email_hint': 'Correio Eletrónico',
      'pass_hint': 'Senha',
      'login_btn': 'Entrar no Sistema',
      'register_btn': 'Criar Conta',
      'settings': 'Configurações',
      'language': 'Idioma',
      'font_size': 'Tamanho da Fonte',
      'notification_target': 'Enviar Alertas Para',
      'theme': 'Aparência (Tema)',
      'logout': 'Sair',
      'delete_account': 'Destruir Conta',
      'alerts': 'Alertas',
      'dashboard': 'Painel de Controle',
      'settings_title': 'Configurações do Sistema',
      'theme_title': 'Aparência del Sistema',
      'theme_subtitle': 'Alternar Modo Claro / Escuro',
      'lang_title': 'Idioma do Sistema',
      'danger_zone': 'ZONA DE PERIGO',
      'danger_zone_desc': 'Excluir sua conta apagará todos os seus dados criptografados do banco de dados local y encerrará sua sessão permanentemente. Esta ação não pode ser desfeita.',
      'delete_account_confirm': 'EXCLUIR CONTA DEFINITIVAMENTE',
      'show_danger_zone': 'Mostrar Zona de Perigo',
      'hide_danger_zone': 'Ocultar Zona de Perigo',
      'danger_zone_sub': 'Opções avançadas de conta',
      'tactical_alerts_log': 'REGISTRO DE ALERTAS TÁCTICO',
      'export_csv': 'EXPORTAR CSV',
      'col_time': 'HORA',
      'col_plate': 'PLACA',
      'col_brand_color': 'MARCA/COR',
      'col_confidence': 'CONFIANÇA',
      'col_status': 'ESTADO',
      'recent_captures': 'CAPTURAS RECENTES',
      'initializing_feed': 'INICIALIZANDO FLUXO DE VÍDEO...',
      'analyzing_traffic': 'ANALISANDO TRÁFEGO...',
    },
  };

  static String of(BuildContext context, String key) {
    final provider = Provider.of<AppProvider>(context, listen: true);
    final lang = provider.language;
    return _localizedValues[lang]?[key] ?? _localizedValues['es']?[key] ?? key;
  }
}
